### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by aletote** [danielathome19/PaGANini#1]
When I run finalProject.py it does nothing.

**Comment by danielathome19** [comment]
Hi there! I've just added a readme to the project describing the usage. Hope that helps, let me know if you have any further questions!

**Comment by aletote** [comment]
music21.converter.ConverterException: File not found or no such format found for: run/compose/0003_presto/output/--------output-20201130-180054.mid

**Comment by danielathome19** [comment]
You'll need to edit that line of code to select a file of your choice from output by the model. If you want to try this without training, I've updated the readme to include the output from my own model, as well as all weights and training datasets.
